export const STORYLY_ROWS = [
  ["India Data Residency", "Available", "Not available"],
  ["INR Billing", "Full INR pricing", "USD only"],
  ["Indian Language Support", "12+ incl. Hindi, Tamil", "Limited"],
  ["Customer Lists Format", "First-class native format", "Not available"],
  ["Gamification Built-in", "Streaks, scratch, spin", "Limited"],
  ["AI Calling Commerce", "Full AI call ordering", "Not available"],
  ["AI Text / Voice Ordering", "WhatsApp + in-app", "Not available"],
  ["AI Content Cataloging", "Auto-enrich via AI", "Not available"],
  ["Shopify App (India)", "Deep native integration", "Basic plugin"],
  ["Meta & Google Sync", "Full bi-directional", "Partial"],
  ["CleverTap/WebEngage Native", "Built-in", "Via middleware"],
  ["Creator Network / Marketplace", "Listerr Network", "Not available"],
  ["No-Code Content Studio", "Storyboard", "Basic editor"],
  ["Seller Command Centre", "Seller Studio", "Not available"],
  ["DPDP Compliance", "Full compliance", "GDPR only"],
  ["Startup-Friendly Entry Price", "From ₹9,999/mo", "Enterprise-first"],
  ["India Customer Support", "Hindi + English, IST", "Global timezone"],
] as const
