/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          listerr: {
            50: "#EBF2FF",
            100: "#D6E5FF",
            200: "#ADC9FF",
            300: "#85ADFF",
            400: "#5C91FE",
            500: "#4280FD",
            600: "#3568D4",
            700: "#2952AB",
            800: "#1E3D82",
            900: "#142A5A",
            950: "#0A1A3D",
          },
          sky: {
            DEFAULT: "#5EBEFF",
            light: "#DEF2FF",
            mid: "#C3E7FE",
          },
          seller: {
            50: "#F0FDFA",
            100: "#CCFBF1",
            200: "#99F6E4",
            300: "#5EEAD4",
            400: "#2DD4BF",
            500: "#0D9488",
            600: "#0F766E",
            700: "#0F5F59",
            800: "#115E59",
            900: "#134E4A",
            950: "#042F2E",
          },
          network: {
            50: "#FFF7ED",
            100: "#FFEDD5",
            200: "#FED7AA",
            300: "#FDBA74",
            400: "#FB923C",
            500: "#EA580C",
            600: "#C2410C",
            700: "#9A3412",
            800: "#7C2D12",
            900: "#431407",
            950: "#431407",
          },
          storyboard: {
            50: "#FDF2F8",
            100: "#FCE7F3",
            200: "#FBCFE8",
            300: "#F9A8D4",
            400: "#F472B6",
            500: "#EC4899",
            600: "#DB2777",
            700: "#BE185D",
            800: "#9D174D",
            900: "#831843",
            950: "#500724",
          },
        },
        bg: {
          DEFAULT: "#FFFFFF",
          subtle: "#FAFAF9",
          muted: "#F5F5F4",
        },
        fg: {
          DEFAULT: "#0C0A09",
          muted: "#5F6368",
          subtle: "#9AA0A6",
        },
        border: {
          DEFAULT: "#E7E5E4",
          strong: "#D6D3D1",
        },
        surface: {
          DEFAULT: "#FFFFFF",
          raised: "#FAFAF9",
          sunken: "#F5F5F4",
        },
        ai: {
          bg: "#0B1020",
          surface: "#111733",
          fg: "#F5F5F4",
          accent: "#FBBF24",
        },
        success: "#16A34A",
        warning: "#D97706",
        destructive: {
          DEFAULT: "#DC2626",
          foreground: "#FFFFFF",
        },
        info: "#0EA5E9",
        input: "#E7E5E4",
        ring: "#4280FD",
        background: "#FFFFFF",
        foreground: "#0C0A09",
        primary: {
          DEFAULT: "#4280FD",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT: "#F5F5F4",
          foreground: "#0C0A09",
        },
        muted: {
          DEFAULT: "#F5F5F4",
          foreground: "#57534E",
        },
        accent: {
          DEFAULT: "#EBF2FF",
          foreground: "#0A1A3D",
        },
        popover: {
          DEFAULT: "#FFFFFF",
          foreground: "#0C0A09",
        },
        card: {
          DEFAULT: "#FFFFFF",
          foreground: "#0C0A09",
        },
      },
      fontFamily: {
        sans: ["var(--font-baloo)", "system-ui", "sans-serif"],
      },
      boxShadow: {
        sm: "0 1px 2px rgb(0 0 0 / 0.04)",
        md: "0 4px 12px rgb(0 0 0 / 0.06)",
        xl: "0 24px 48px rgb(0 0 0 / 0.08)",
      },
      borderRadius: {
        lg: "12px",
        md: "8px",
        sm: "4px",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0) scale(1)" },
          "50%": { transform: "translateY(-24px) scale(1.05)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(251,191,36,0.15)" },
          "50%": { boxShadow: "0 0 40px rgba(251,191,36,0.35)" },
        },
        "gradient-shift": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(32px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        marquee: "marquee 35s linear infinite",
        float: "float 6s ease-in-out infinite",
        "float-slow": "float 10s ease-in-out infinite",
        "float-delayed": "float 8s ease-in-out 2s infinite",
        shimmer: "shimmer 2.5s ease-in-out infinite",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "gradient-shift": "gradient-shift 4s ease infinite",
        "fade-in-up": "fade-in-up 0.7s cubic-bezier(0.16,1,0.3,1) forwards",
        "scale-in": "scale-in 0.6s cubic-bezier(0.16,1,0.3,1) forwards",
        "spin-slow": "spin-slow 20s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
