import type { MetadataRoute } from "next"

const routes = [
  "/",
  "/platform",
  "/features",
  "/pricing",
  "/integrations",
  "/listerr",
  "/seller-studio",
  "/seller-studio/catalogue",
  "/seller-studio/content",
  "/seller-studio/orders",
  "/seller-studio/ads",
  "/seller-studio/analytics",
  "/network",
  "/network/creators",
  "/network/brands",
  "/network/agencies",
  "/network/publishers",
  "/network/apply",
  "/storyboard",
  "/storyboard/templates",
  "/storyboard/ai-editor",
  "/storyboard/pricing",
  "/use-cases/stories",
  "/use-cases/reels",
  "/use-cases/customer-lists",
  "/use-cases/gamification",
  "/use-cases/ai-personalisation",
  "/use-cases/smart-flows",
  "/use-cases/meta-google-sync",
  "/use-cases/shopify",
  "/ai/ai-calling",
  "/ai/text-ordering",
  "/ai/voice-ordering",
  "/ai/listerr-order",
  "/ai/content-cataloging",
  "/industries/ecommerce",
  "/industries/edtech",
  "/industries/fintech",
  "/industries/media-ott",
  "/industries/food-delivery",
  "/industries/travel",
  "/blog",
  "/case-studies",
  "/docs",
  "/docs/getting-started",
  "/about",
  "/careers",
  "/contact",
  "/partners",
  "/press-kit",
  "/changelog",
  "/vs/storyly",
  "/privacy",
  "/terms",
  "/cookies",
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return routes.map((route) => ({
    url: `https://listerr.in${route}`,
    lastModified: now,
    changeFrequency: route === "/" ? "weekly" : "monthly",
    priority: route === "/" ? 1 : route.includes("sample") ? 0.5 : 0.8,
  }))
}
