import type { Metadata } from "next"
import { FileSpreadsheet, Gauge, Image, LinkIcon, PenLine, ShoppingBag, Tags, Wand2 } from "lucide-react"
import { AIPage } from "@/components/ai/ai-page"

export const metadata: Metadata = { title: "AI Content Cataloging", description: "AI product cataloging from images, URLs, CSVs, and Shopify sync." }

export default function Page() {
  return <AIPage title="From Raw Product Data to a Rich, Structured, Searchable Catalogue — Automatically" subtitle="Upload images, paste URLs, import CSV — AI enriches everything that powers Stories, Reels, Ads, AI ordering, and SEO." steps={["Import images, URLs, CSV, Excel, or Shopify products.","AI identifies product type, attributes, and missing fields.","Descriptions, tags, and catalogue schema are generated.","Images are checked and enhanced for commerce surfaces.","Catalogue health score guides fixes before publishing."]} capabilities={[{title:"Image Upload",description:"AI identifies product attributes and suggests title and description.",icon:Image},{title:"URL Scraping",description:"Paste a URL and AI extracts structured product data.",icon:LinkIcon},{title:"CSV Import",description:"Cleanse, enrich, and map columns to Listerr schema.",icon:FileSpreadsheet},{title:"Shopify Sync",description:"Pull products, variants, images, and inventory live.",icon:ShoppingBag},{title:"Auto Descriptions",description:"SEO-optimised, brand-tone, multilingual copy.",icon:PenLine},{title:"Smart Tags",description:"Category, occasion, season, audience, and style.",icon:Tags},{title:"Image Enhancement",description:"Background, aspect ratio, and quality checks.",icon:Wand2},{title:"Health Score",description:"Completeness, quality, SEO, and actions.",icon:Gauge}]} useCases={["Sellers with 1,000+ SKUs go live in hours, not weeks.","Eliminate cataloguing bottlenecks that block adoption.","Power Stories, Reels, Lists, Ads, AI ordering, and SEO from one enriched catalogue.","Improve personalisation performance with structured product data."]} channels={["Shopify","CSV","Excel","Image upload","Product URLs","Seller Studio"]} pricing="₹2,000/month up to 5,000 SKUs · Add-on for all plans" />
}
